In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
usr = pd.read_csv('/content/drive/MyDrive/Datasets/Data_High_Low.csv')

In [ ]:
usr

Product  Month  Year     Open     High      Low    Close  NextVal  \
0           beans      1  2007   794.74   823.10   776.51   799.71   804.81   
1           beans      2  2007   804.81   828.80   781.37   802.21   806.83   
2           beans      3  2007   806.83   827.97   785.69   807.49   812.18   
3           beans      4  2007   812.18   830.88   793.48   810.26   815.14   
4           beans      5  2007   815.14   831.77   798.50   815.24   820.25   
...           ...    ...   ...      ...      ...      ...      ...      ...   
3412  wheat_flour      5  2023  2431.35  2495.82  2365.69  2419.25  2433.05   
3413  wheat_flour      6  2023  2433.05  2491.78  2374.92  2442.94  2457.43   
3414  wheat_flour      7  2023  2457.43  2512.63  2403.74  2472.47  2489.38   
3415  wheat_flour      8  2023  2489.38  2540.84  2437.65  2483.28  2497.20   
3416  wheat_flour      9  2023  2497.20  2547.68  2448.22  2515.86  2535.13   

      NextHigh  NextLow  
0       828.80   781.37  
1       827.97   785.69  
2       830.88   793.48  
3       831.77   798.50  
4       835.70   803.72  
...        ...      ...  
3412   2491.78  2374.92  
3413   2512.63  2403.74  
3414   2540.84  2437.65  
3415   2547.68  2448.22  
3416   2585.13  2484.71  

[3417 rows x 10 columns]

In [ ]:
usr = usr[['Product', 'Year', 'Month','Open', 'High', 'Low', 'Close','NextVal', 'NextHigh', 'NextLow']]

In [ ]:
usr.Product.unique()

array(['beans', 'cassava', 'cassava_flour', 'fish', 'fish_salted',
       'fish_smoked', 'maize', 'maize_meal', 'meat_beef', 'meat_chicken',
       'meat_goat', 'oil', 'plantains', 'rice', 'salt', 'sugar',
       'wheat_flour'], dtype=object)

In [ ]:
usr = pd.get_dummies(usr, columns = ['Product'])  #One Hot Encoding
usr

Year  Month     Open     High      Low    Close  NextVal  NextHigh  \
0     2007      1   794.74   823.10   776.51   799.71   804.81    828.80   
1     2007      2   804.81   828.80   781.37   802.21   806.83    827.97   
2     2007      3   806.83   827.97   785.69   807.49   812.18    830.88   
3     2007      4   812.18   830.88   793.48   810.26   815.14    831.77   
4     2007      5   815.14   831.77   798.50   815.24   820.25    835.70   
...    ...    ...      ...      ...      ...      ...      ...       ...   
3412  2023      5  2431.35  2495.82  2365.69  2419.25  2433.05   2491.78   
3413  2023      6  2433.05  2491.78  2374.92  2442.94  2457.43   2512.63   
3414  2023      7  2457.43  2512.63  2403.74  2472.47  2489.38   2540.84   
3415  2023      8  2489.38  2540.84  2437.65  2483.28  2497.20   2547.68   
3416  2023      9  2497.20  2547.68  2448.22  2515.86  2535.13   2585.13   

      NextLow  Product_beans  ...  Product_maize_meal  Product_meat_beef  \
0      781.37              1  ...                   0                  0   
1      785.69              1  ...                   0                  0   
2      793.48              1  ...                   0                  0   
3      798.50              1  ...                   0                  0   
4      803.72              1  ...                   0                  0   
...       ...            ...  ...                 ...                ...   
3412  2374.92              0  ...                   0                  0   
3413  2403.74              0  ...                   0                  0   
3414  2437.65              0  ...                   0                  0   
3415  2448.22              0  ...                   0                  0   
3416  2484.71              0  ...                   0                  0   

      Product_meat_chicken  Product_meat_goat  Product_oil  Product_plantains  \
0                        0                  0            0                  0   
1                        0                  0            0                  0   
2                        0                  0            0                  0   
3                        0                  0            0                  0   
4                        0                  0            0                  0   
...                    ...                ...          ...                ...   
3412                     0                  0            0                  0   
3413                     0                  0            0                  0   
3414                     0                  0            0                  0   
3415                     0                  0            0                  0   
3416                     0                  0            0                  0   

      Product_rice  Product_salt  Product_sugar  Product_wheat_flour  
0                0             0              0                    0  
1                0             0              0                    0  
2                0             0              0                    0  
3                0             0              0                    0  
4                0             0              0                    0  
...            ...           ...            ...                  ...  
3412             0             0              0                    1  
3413             0             0              0                    1  
3414             0             0              0                    1  
3415             0             0              0                    1  
3416             0             0              0                    1  

[3417 rows x 26 columns]

In [ ]:
predictors = ["Year", "Month", 'Product_beans', 'Product_cassava', 'Product_cassava_flour', 'Product_fish', 'Product_fish_salted',
       'Product_fish_smoked', 'Product_maize', 'Product_maize_meal', 'Product_meat_beef', 'Product_meat_chicken',
       'Product_meat_goat', 'Product_oil', 'Product_plantains', 'Product_rice', 'Product_salt', 'Product_sugar',
       'Product_wheat_flour',"Open","High","Low"]
target = ["NextVal", "NextHigh", "NextLow"]

In [ ]:
train = usr[usr["Year"]<2020].copy()
test = usr[usr["Year"]>=2020].copy()

In [ ]:
X_train = train[predictors]
X_test = test[predictors]
y_train = train[target]
y_test = test[target]

In [ ]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

In [ ]:
reg.fit(X_train, y_train)

LinearRegression()

In [ ]:
w = reg.coef_[0]
b = reg.intercept_

In [ ]:
w

array([ -0.24696088,   0.59454605,   4.80483914,   5.89550665,
         5.09304037,  -1.55710229, -42.39593951, -43.17485726,
         6.17542141,   6.57678895,   8.75567924,  20.6694658 ,
        -0.14579556,   6.68550184,   2.14756478,   6.95004871,
         6.33761605,   3.35416248,   3.82805921,  -2.59242007,
         1.77373905,   1.82596969])

In [ ]:
b

array([  487.5712989 , -1753.53379451,   343.81381115])

In [ ]:
predictions = reg.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error

error = mean_absolute_error(predictions, y_test)

In [ ]:
error

39.619793380038566

In [ ]:
reg.predict([[2025,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,887.73,918.99,856.44]])
#"Year", "Month", 'Product_beans', 'Product_cassava', 'Product_cassava_flour', 'Product_fish', 'Product_fish_salted',
 #      'Product_fish_smoked', 'Product_maize', 'Product_maize_meal', 'Product_meat_beef', 'Product_meat_chicken',
  #     'Product_meat_goat', 'Product_oil', 'Product_plantains', 'Product_rice', 'Product_salt', 'Product_sugar',
   #    'Product_wheat_flour',"Open","High","Low"

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[886.47842512, 922.55290781, 845.27774096]])

In [ ]:
predictions_df = pd.DataFrame(columns=target)

o= 2362.13
h= 2476
l= 2249.67

for year in range(2024,2030):
  for month in range(1,13):
    pre = reg.predict([[year,month,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,o,h,l]])
    print(pre)
    o = pre[0][0]
    h = pre[0][1]
    l = pre[0][2]
    prediction_df = pd.DataFrame(pre, columns=target, index=[pd.to_datetime(f"{year}-{month}-01")])
    predictions_df = pd.concat([predictions_df, prediction_df])

# Saving predictions to a CSV file
predictions_df.to_csv("oil.csv")

[[2370.9764186  2486.77751717 2236.77418229]]
[[2344.20646225 2469.17708531 2204.06008459]]
[[2323.24645631 2456.80332583 2177.30546845]]
[[2307.3772039  2449.12985622 2155.91654814]]
[[2296.44526551 2446.07844403 2139.66887467]]
[[2290.29981978 2447.56443685 2128.35286416]]
[[2288.79901399 2453.50305994 2121.77614295]]
[[2291.80895317 2463.80960405 2119.76149191]]
[[2299.20290049 2478.39965361 2122.14510475]]
[[2310.86057456 2497.18927944 2128.77506531]]
[[2326.66753245 2520.09520162 2139.51001641]]
[[2346.51462759 2547.03492657 2154.2179959 ]]
[[2362.91601923 2555.44363178 2158.61405508]]
[[2343.93318798 2536.78790006 2141.76149516]]
[[2329.87654328 2523.62330008 2128.94134235]]
[[2320.15204166 2515.39789347 2119.81416583]]
[[2314.7009083  2511.99956086 2114.36814022]]
[[2313.45504894 2513.31434456 2112.57910433]]
[[2316.3447437  2519.23199898 2114.41628691]]
[[2323.2990015  2529.6456855  2119.84331838]]
[[2334.24594745 2544.45176901 2128.81916001]]
[[2349.11315437 2563.54963462 2141

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature n